AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  ScoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Scores
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.handler
      Runtime: python3.11
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ScoresTable
      Environment:
        Variables:
          SCORES_TABLE: !Ref ScoresTable
      Architectures:
      - x86_64
      Events:
        GetScore:
          Type: Api
          Properties:
            Path: /score/{id}
            Method: get
        PostScore:
          Type: Api
          Properties:
            Path: /score
            Method: post

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: health/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: get


Outputs:
  ApiBaseUrl:
    Description: Base API Gateway URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod"